### PR TITLE
Typescript parsing

### PR DESCRIPTION
**Pull request by Shin--**
Clean new PR (More info can be found in https://github.com/Polyconseil/easygettext/pull/76)
- Added TypeScript support (https://github.com/buntis/buntis)
- TypeScript tests

@vperron I also changed some things today that I have mentioned here: https://github.com/Polyconseil/easygettext/pull/76#issuecomment-596505115

### CODE REVIEW

**Comment by vperron** [comment]
There are still conflicts though, do you think you fix these ?

**Comment by Shin--** [comment]
> There are still conflicts though, do you think you fix these ?

Where are you seeing conflicts? I cleaned my branch, merged the latest master into it and then created this PR. Git also says: "This branch has no conflicts with the base branch"

**Comment by vperron** [comment]
We don't have the same Github then :)
Screenshot from 2020-03-09 14-45-07

**Comment by Shin--** [comment]
Oh, that is strange. I would resolve them, but this is how it looks to me:
grafik
How I understand it is that there are no files that need to be merged but that git itself has a problem. Since I can't merge it (no permissions), I am not seeing this message. This must still be because of the initial branch... it has been years since git has caused me so much trouble... I will look into it later today.

**Comment by vperron** [comment]
Yep, I guess you're right :) This wouldn't be the first time GH messes up with this though. Have you ever looked at the commit order ? :D

Whenever, please do ! Or I'll try and rebase myself at some point with a good old vim.

**Comment by vperron** [comment]
Do you need any help with this ?

**Comment by Shin--** [comment]
@vperron Sorry for the delay, I didn't get around fixing it until now. I rebased the branch and committed it. I think it should work now!

**Pull request merged**
