### PR TITLE
Add filter parameters & fix JS & HTML extraction

### PR DESCRIPTION
**Pull request by vperron**
Rebased & squashed version of @torfeld6  pull request, created so that we can check it can be merged properly.

### CODE REVIEW

**Comment by Knogobert** [comment]
@vperron , should the URL really have been changed to the fork URL in package.json?

```
  "main": "src/extract-cli.js",
  "repository": {
    "type": "git",
-    "url": "https://github.com/polyconseil/easygettext"
+    "url": "https://github.com/PitcherAG/easygettext"
  },
```

This might possibly be part of #93

**Comment by vperron** [comment]
Damn, I was looking into this issue on npmjs, I think I overlloked that :(

It's of course a mistake... I'll fix that

**Comment by torfeld6** [comment]
I can write a test for and resolve the issue #93 this afternoon, since it was most likely caused by my PR.

**Comment by vperron** [comment]
Fantastic ! I you can do so that would help a lot as I was envisioning creating a new release tonight :partying_face:

**Pull request merged**
