### PR TITLE
add filter parameters

### PR DESCRIPTION
**Pull request by torfeld6**
### Added
- Regex for filter parameters `{{ "Hello %s" | i18n("World") }}`
- Support for `_` function of older i18n libraries https://github.com/Blakko/jquery-i18n

### Changed
- preprocessScript's returned items always have a language set
- extract according to changed preprocessScript 

### Fixed
- HTML broken since 2.10.0 #85
- JavaScript broken
- Undefined vueFile.script.lang (extract.spec.js:109 failed)
- preprocessTemplate parsed `/* <template> */` in JavaScript

### CODE REVIEW

**Comment by janlazo** [comment]
Is this ready?

**Comment by Shin--** [comment]
@vperron Do you have time to look into this?

**Comment by vperron** [comment]
Of course ! I'm very sorry, I was not super available and forgot about that ! 

I'll try an rebase it.

**Comment by vperron** [comment]
@Shin-- @torfeld6  if that is fine by you I'll merge the rebased version @89  tomorrow.

**Comment by torfeld6** [comment]
Of course. I wasn’t sure what you meant by rebase.

**Comment by vperron** [comment]
The 2.14.0 contains your changes !

**Pull request closed without merging**
