### PR TITLE
Allow glob paths arguments

### PR DESCRIPTION
**Pull request by Hyzual**
Hi, first of all, thank you very much for this great library ! We had lots of troubles with basic xgettext so this really saved our day while using gettext for VueJS.

I would like to propose some changes to the extract CLI. We currently use it in an npm script to extract strings from all files of our app. As we do not particularly want to use the compile CLI (we use a webpack loader to just load the translations we need), we use the extract CLI directly.

The extract CLI needs "exact" file paths. It is unfortunate because I would prefer not to have to change my npm script every time we add a file and so, up until now we just passed a path with a star, for example `src/*.vue`. Our shell expanded it, everyone was happy, the end.

But as our Vue apps get larger, we're starting to have sub-folders, and now we need to get all .vue file paths recursively. This requires options in bash. As a workaround, we could use a package from npm to convert globstar paths for us.

I think nonetheless that it would be sensible for gettext-extract to support paths with globs. What do you think about it ?

I've submitted this PR with an implementation using [fast-glob](https://www.npmjs.com/package/fast-glob). Let me know if something's missing or if the approach I'm taking is wrong or if you have any feedback.

How to test:

 ./src/extract-cli.js <a path with globs> <another path with globs>

It should extract translations from all the files according to the given
glob. If using globstar (**/*) then, it should extract translations from
all files in subdirectories.

Note: it would probably make sense to use streams instead of synchronous files but that's work for another day ;).

### CODE REVIEW

**Comment by Hyzual** [comment]
FYI we used the `find` command to supply filenames to gettext-extract, so maybe just a mention in the README and an example would be enough:

Example `package.json`
```json
{
  "scripts": {
    "extract-gettext-cli": "gettext-extract --attribute v-translate $(find repositories/src/components/ -type f -name '*.vue')"
  }
}
```

**Comment by vperron** [comment]
Hi, I'm sorry I was on vacation with a very limited internet access.

I'll be able to read this tomorrow. But from my very first point of view, this globbing seems not to be the responsibility of easygettext, which is supposed to be kept as minimal as possible :)

I indeed would much prefer the `find` option (or whatever you please) instead of adding to much magic to the code, don't you think ? It's a token extractor, not especially a file finder.

**Comment by Hyzual** [comment]
Hi, yeah don't worry about it ! Enjoy your vacation :)
Indeed, after submitting I thought that maybe it was adding a responsibility that might not be needed.

Another alternative could be to split into two packages, `easygettext` and `easygettext-cli` with the latter being solely responsible for the CLI part. For example [webpack-cli](https://github.com/webpack/webpack-cli).

But I understand it's a lot of work; I would be happy with just a mention of the `find` trick to help people extract from nested folders :).

**Comment by vperron** [comment]
Aha, if you're willing to open a PR that does just that part (documentation) I'll merge it in a whoosh !!

**Comment by Hyzual** [comment]
Hey, I've finally gotten around to writing the example at #47

**Pull request closed without merging**
