### PR TITLE
Fix jade file render options in case when 'include' have absolute path

### LINKED ISSUE #14: Error on 'include' in Jade template with abs path
``include someAbsPath`` causing error ``the "filename" option is required to use "include" with "relative" paths `` in ``jade.render`` method.

### PR DESCRIPTION
**Pull request by ivanzvakoms**
Closes #14

### CODE REVIEW

**Comment by vperron** [comment]
Nice one ! Do you think you could add a test case to ensure it works ?

**Comment by ivanzvakoms** [comment]
@vperron ok, will do

**Comment by vperron** [comment]
Would merge right after, but for now I'm not sure it breaks or works somehow :)

**Comment by vperron** [comment]
I'll just merge it but someone will have to write a test later on :)

**Pull request merged**
